/**
 * NLP Enrichment Service
 * 
 * Provides O(1) lookups for NLP data (aliases, slang, movement patterns, intent triggers)
 * using pre-built hash maps generated by scripts/build-nlp-indexes.ts.
 * 
 * Usage:
 *   import { nlpIndexes, lookupByAlias, getMovementPatternForExercise } from './nlp-enrichment';
 */

// Import pre-built indexes (generated file)
import indexesData from '@/data/hevy-nlp-indexes.json';

// ============================================
// TYPES
// ============================================

export interface MovementPattern {
    pattern_id: string;
    canonical_name: string;
    description: string;
    icon: string;
    default_exercise_id: string;
    exercises: string[]; // Exercise names (for pattern matching, not full TaxonomyExercise)
}

export interface SlangEntry {
    direct_match?: string;
    description?: string;
}

export interface ExerciseNLP {
    progression?: string;
    regression?: string;
    siblings?: string[];
    clarificationQuestion?: string;
    options?: Array<{ id: string; label: string; default?: boolean }>;
}

export interface HevyNLPIndexes {
    version: string;
    generatedAt: string;
    stats: {
        aliasCount: number;
        slangCount: number;
        patternCount: number;
        intentCount: number;
        exerciseNLPCount: number;
    };
    aliasMap: Record<string, string>;
    slangDictionary: Record<string, SlangEntry>;
    movementPatterns: MovementPattern[];
    intentTriggers: Record<string, string[]>;
    exerciseNLP: Record<string, ExerciseNLP>;
}

// ============================================
// SINGLETON INDEXES (lazy loaded at import)
// ============================================

export const nlpIndexes: HevyNLPIndexes = indexesData as HevyNLPIndexes;

// Pre-built exercise → pattern index for fast lookups
const _exerciseToPattern: Map<string, MovementPattern> = new Map();
let _patternIndexBuilt = false;

function buildPatternIndex(): void {
    if (_patternIndexBuilt) return;

    for (const pattern of nlpIndexes.movementPatterns) {
        for (const exercise of pattern.exercises) {
            const key = exercise.toLowerCase();
            if (!_exerciseToPattern.has(key)) {
                _exerciseToPattern.set(key, pattern);
            }
        }
    }
    _patternIndexBuilt = true;
}

// ============================================
// O(1) LOOKUP FUNCTIONS
// ============================================

/**
 * Look up canonical exercise name by alias (O(1))
 * Handles: aliases, slang terms, misspellings
 */
export function lookupByAlias(alias: string): string | null {
    const key = alias.toLowerCase().trim();
    return nlpIndexes.aliasMap[key] ?? null;
}

/**
 * Get slang dictionary entry (O(1))
 */
export function lookupSlang(term: string): SlangEntry | null {
    const key = term.toLowerCase().trim();
    return nlpIndexes.slangDictionary[key] ?? null;
}

/**
 * Get movement pattern for an exercise (O(1))
 */
export function getMovementPatternForExercise(exerciseName: string): MovementPattern | null {
    buildPatternIndex();
    return _exerciseToPattern.get(exerciseName.toLowerCase()) ?? null;
}

/**
 * Get all movement patterns
 */
export function getAllMovementPatterns(): MovementPattern[] {
    return nlpIndexes.movementPatterns;
}

/**
 * Get movement patterns filtered by body region (O(n) where n = ~15 patterns)
 */
export function getRelatedPatterns(bodyRegion?: string): MovementPattern[] {
    if (!bodyRegion) {
        return nlpIndexes.movementPatterns;
    }

    const region = bodyRegion.toLowerCase();

    // Map body regions to pattern keywords
    const regionPatternMap: Record<string, string[]> = {
        chest: ['BENCH', 'PUSH'],
        back: ['ROW', 'PULL', 'DEADLIFT'],
        shoulders: ['PRESS', 'RAISE', 'PUSH'],
        legs: ['SQUAT', 'LUNGE', 'LEG'],
        arms: ['CURL', 'EXTENSION', 'TRICEPS'],
        core: ['PLANK', 'CRUNCH', 'AB'],
    };

    const keywords = regionPatternMap[region] || [];
    if (keywords.length === 0) {
        return nlpIndexes.movementPatterns;
    }

    return nlpIndexes.movementPatterns.filter(pattern =>
        keywords.some(kw => pattern.pattern_id.includes(kw))
    );
}

/**
 * Get exercises matching an intent (O(1))
 */
export function getIntentMatches(intent: string): string[] {
    const key = intent.toLowerCase().trim();
    return nlpIndexes.intentTriggers[key] ?? [];
}

/**
 * Get NLP enrichment data for an exercise (O(1))
 */
export function getExerciseNLP(exerciseName: string): ExerciseNLP | null {
    return nlpIndexes.exerciseNLP[exerciseName] ?? null;
}

/**
 * Get progression exercise (O(1))
 */
export function getProgression(exerciseName: string): string | null {
    const nlp = getExerciseNLP(exerciseName);
    return nlp?.progression ?? null;
}

/**
 * Get regression exercise (O(1))
 */
export function getRegression(exerciseName: string): string | null {
    const nlp = getExerciseNLP(exerciseName);
    return nlp?.regression ?? null;
}

/**
 * Get sibling exercises (O(1))
 */
export function getSiblings(exerciseName: string): string[] {
    const nlp = getExerciseNLP(exerciseName);
    return nlp?.siblings ?? [];
}

// ============================================
// DEBUG / STATS
// ============================================

export function getNLPStats(): typeof nlpIndexes.stats {
    return nlpIndexes.stats;
}

export function logNLPStats(): void {
    console.log('[NLP Enrichment] Loaded indexes:');
    console.log(`  - Aliases: ${nlpIndexes.stats.aliasCount}`);
    console.log(`  - Slang entries: ${nlpIndexes.stats.slangCount}`);
    console.log(`  - Movement patterns: ${nlpIndexes.stats.patternCount}`);
    console.log(`  - Intent triggers: ${nlpIndexes.stats.intentCount}`);
    console.log(`  - Exercise NLP: ${nlpIndexes.stats.exerciseNLPCount}`);
}
